### ISSUE TITLE
Support for Watchify

### ISSUE THREAD

**Issue by gCardinal** [JS-DevTools/sourcemapify#1]
When using this plugin with Watchify, the first time the bundle gets compiled, the relative paths will have been properly written, but any further change to the watched files will revert back to the default of using absolute paths.

For reference, this is the command I use to initialize watchify: `bin/watchify -d -v -p tsify -p [ sourcemapify --root "../../" ] -t debowerify js/tests/karma/**/*.ts -o \'bin/exorcist js/compiled/tests.js.map > js/compiled/tests.js\'`

Is this something on Watchify's part or is there something special this plugin should do to have support for Watchify? Is it even a bug/missing feature or am I just not using the plugin properly? If so, maybe updating the doc would be useful.

**Comment by JamesMessinger** [comment]
Thanks for pointing this out!  I somehow hadn't noticed it before, but the same thing is happening in all of my projects where I'm using this plugin.   I guess I never noticed because whenever I stop and restart Watchify, the problem fixes itself.

Anyway... I think I have an idea of what's causing the bug and how to fix it.  I'll look into it more today or tomorrow

**Comment by gCardinal** [comment]
I've been digging around a bit (mind you, I'm very new to Browserify and all that, so my knowledge, and sadly debugging skills, is limited) and so far, I've found that hooking into the `debug` pipeline works only on initialization. So, this `browserify.pipeline.get('debug').push(transformStream);` will only ever be called once, even though Browserify _will_ update the source maps every time a watched file is updated. Which causes the relative paths to vanish out of existence!

I'm sure you already knew that much, but I figured I'd still point it out, just in case.

So far, digging into Browserify's source, I can't really guess at why you only get the debug pipeline once. I threw a quick and dirty `console.log()` in `Browserify.prototype._debug` (line 732 of `index.js` in Browserify's source) and this is called every time Watchify updates the bundle.

Aaaand that's where I am right now. Just figured I'd update this since you replied! I'll let you know if I manage to hack a working solution together.

**Comment by JamesMessinger** [comment]
Thanks for the info.  I actually _didn't_ know that, so it's very helpful.  My hunch was that my _was_ being called every time, but that the paths had already been modified from the previous call, so I would need to detect that and not modify them again.  Sounds like my hunch was wrong.
