### ISSUE TITLE
Please update deps

### ISSUE THREAD

**Issue by grigorii-horos** [JS-DevTools/sourcemapify#3]

**Comment by JamesMessinger** [comment]
The dependencies are already [up-to-date](https://david-dm.org/BigstickCarpet/sourcemapify).  A couple of the [dev-dependencies](https://david-dm.org/BigstickCarpet/sourcemapify?type=dev) are outdated, but that doesn't affect the functionality of the library.

Nonetheless, I'll add it to my to-do list to update the dev-dependencies soon.
